### ISSUE TITLE
Noise growth rate ablation

### ISSUE THREAD

**Issue by prclibo** [matejgrcic/DenseFlow#3]
Hi, thanks for this great work! I was recently researching on the effect of augmentation noise.

My intuition is that larger growth rate will result in larger capacity of the model. However, by altering DF_74_10 to DF_74_50, I observe that the convergence becomes extremely slow than DF_74_10. I was wondering if you could share any experience on the selection of growth rate. :-)

**Comment by matejgrcic** [comment]
Hi,

We set the growth rate to 10 early in our experiments and did not conduct an intensive hyperparameter search due to limited computational resources.
Still, the cause of slow convergence might be found by looking at equation (9) from our paper.
If we radically increase the dimensionality of the augmentation noise, the term ln p*(**e**_i) would dominate the expression.
The noise is sampled from the fully factorised Gaussian, meaning that ln p*(**e**_i) = sum_j ln p(e_i^j) = sum_j ln N(e_i^j; 0, 1).

Hope this helps.

**Comment by prclibo** [comment]
> Hi, thanks for this great work! I was recently researching on the effect of augmentation noise.
> 
> My intuition is that larger growth rate will result in larger capacity of the model. However, by altering DF_74_10 to DF_74_50, I observe that the convergence becomes extremely slow than DF_74

Thanks for the comments!

**Comment by prclibo** [comment]
FYI, after a very slow run of half a month since the last post. I reached BPD=3.34 at 350 epochs. 🥲

**Comment by matejgrcic** [comment]
Could you give some more info? Is that performance of DenseFlow_74_50 on ImageNet32 or CIFAR10?

**Comment by prclibo** [comment]
> Could you give some more info? Is that performance of DenseFlow_74_50 on ImageNet32 or CIFAR10?

It is DenseFlow_74_50 on CIFAR10. Let me know if you have any comments. Cuz I think this might be helpful to increase flow performance:)

**Comment by matejgrcic** [comment]
Perhaps [this](https://github.com/matejgrcic/DenseFlow/issues/4#issuecomment-1096748166) might help you in improving DenseFlow performance.
